from wpilib import Color, AddressableLED, LEDPattern
from wpimath.units import meters_per_second
from frc3484.leds import ColorStack, ColorWave, FallingSand, Fire

from enum import Enum

class PatternState(Enum):
    fill = 0,
    empty = 1

class LEDSubsystem:
    def __init__(self, _led_pwm_port: int, led_strip_length: int) -> None:
        self._leds = _led_pwm_port
        self._solid_algae = LEDPattern.solid()
        self._solid_coral = ...
        self._solid_orange = ...
        self._solid_team = ...
        self._solid_fire = ...
        self._solid_snow = ...
        self._solid_ice = ...
        self._solid_charged = ...
        self._solid_static = ...
        self._solid_ancient = ...
