# Subsystems
DRIVETRAIN_ENABLED: bool = True
VISION_ENABLED: bool = False

CLIMBER_ENABLED: bool = False
FLYWHEEL_ENABLED: bool = True
FEEDER_ENABLED: bool = True
INDEXER_ENABLED: bool = True
INTAKE_ENABLED: bool = True
TURRET_ENABLED: bool = False
FEED_TARGET_ENABLED: bool = True
LEDS_ENABLED: bool = True

LAUNCH_WHILE_MOVING_ENABLED: bool = False